// Copyright (c) 2026 WSO2 LLC (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/ai;
import ballerina/ai.observe;
import ballerina/http;
import ballerina/jballerina.java;

const DEFAULT_GEMINI_SERVICE_URL = "https://generativelanguage.googleapis.com/v1beta";
const DEFAULT_MAX_TOKEN_COUNT = 512;
const DEFAULT_TEMPERATURE = 0.7d;

# Header used to authenticate Gemini API requests with an API key.
const API_KEY_HEADER = "x-goog-api-key";

# Roles understood by the Gemini `contents` array.
const GEMINI_ROLE_USER = "user";
const GEMINI_ROLE_MODEL = "model";

# JSON-schema keywords that the Gemini function-declaration / response schema
# does not accept; stripped before sending tool parameters or a `responseSchema`.
# Gemini only accepts a subset of OpenAPI 3.0 (type, format, description, nullable,
# enum, items, properties, required, ...), so metadata keywords, `$ref`/`$defs`
# indirection, and validation keywords like `default`/`const` are removed. Note
# that stripping `$ref`/`$defs` drops the reference rather than resolving it, so
# `$ref`-based (nested-record) tool schemas degrade to an unconstrained object.
final string[] & readonly UNSUPPORTED_SCHEMA_KEYS = [
    "$schema",
    "$id",
    "$comment",
    "$anchor",
    "$ref",
    "$defs",
    "definitions",
    "title",
    "default",
    "const",
    "additionalProperties"
];

# ModelProvider is a client class that provides an interface for interacting with Gemini Large Language Models.
public isolated distinct client class ModelProvider {
    *ai:ModelProvider;
    // A single raw HTTP client posts JSON to the Gemini `:generateContent` API.
    private final http:Client httpClient;
    private final string apiKey;
    private final GEMINI_MODEL_NAMES modelName;
    private final decimal temperature;
    private final int maxTokens;
    private final decimal? topP;
    private final int? topK;

    # Initializes the Gemini model with the given connection configuration and model configuration.
    #
    # + apiKey - The Gemini API key
    # + modelName - The Gemini model name
    # + serviceUrl - The base URL of Gemini API endpoint
    # + maxTokens - The upper limit for the number of tokens in the response generated by the model
    # + temperature - The temperature for controlling randomness in the model's output
    # + topP - Nucleus sampling threshold; the model considers tokens whose cumulative
    #          probability mass is within this value. Left unset when `()`
    # + topK - Top-k sampling limit; the model samples from the `topK` most probable
    #          tokens. Left unset when `()`
    # + connectionConfig - Additional HTTP connection configuration
    # + return - `()` on successful initialization; otherwise, returns an `ai:Error`
    public isolated function init(@display {label: "API Key"} string apiKey,
            @display {label: "Model Name"} GEMINI_MODEL_NAMES modelName,
            @display {label: "Service URL"} string serviceUrl = DEFAULT_GEMINI_SERVICE_URL,
            @display {label: "Maximum Tokens"} int maxTokens = DEFAULT_MAX_TOKEN_COUNT,
            @display {label: "Temperature"} decimal temperature = DEFAULT_TEMPERATURE,
            @display {label: "Top P"} decimal? topP = (),
            @display {label: "Top K"} int? topK = (),
            @display {label: "Connection Configuration"} *ConnectionConfig connectionConfig) returns ai:Error? {
        // `ConnectionConfig` is a field-compatible subset of `http:ClientConfiguration`
        // (it omits `auth` because Gemini authenticates via the `x-goog-api-key`
        // header, set per request), so it can be spread directly.
        http:Client|error httpClient = new (serviceUrl, {...connectionConfig});
        if httpClient is error {
            return error ai:Error("Failed to initialize the Gemini client", httpClient);
        }
        self.httpClient = httpClient;
        self.apiKey = apiKey;
        self.modelName = modelName;
        self.temperature = temperature;
        self.maxTokens = maxTokens;
        self.topP = topP;
        self.topK = topK;
    }

    # Sends a chat request to the Gemini model with the given messages and tools.
    #
    # + messages - List of chat messages or a single user message
    # + tools - Tool definitions to be used for the tool call
    # + stop - Stop sequence to stop the completion
    # + return - Function to be called, chat response or an error in-case of failures
    isolated remote function chat(ai:ChatMessage[]|ai:ChatUserMessage messages, ai:ChatCompletionFunctions[] tools = [],
            string? stop = ()) returns ai:ChatAssistantMessage|ai:Error {
        observe:ChatSpan span = observe:createChatSpan(self.modelName);
        span.addProvider("gemini");
        if stop is string {
            span.addStopSequence(stop);
        }
        span.addTemperature(self.temperature);
        json|ai:Error inputMessage = convertMessageToJson(messages);
        if inputMessage is json {
            span.addInputMessages(inputMessage);
        }

        GenerateContentRequest|ai:Error request = self.buildGenerateContentRequest(messages, tools, stop);
        if request is ai:Error {
            span.close(request);
            return request;
        }

        map<string|string[]> headers = {[API_KEY_HEADER]: self.apiKey};
        string path = string `/models/${self.modelName}:generateContent`;
        GenerateContentResponse|error response = self.httpClient->post(path, request, headers);
        if response is error {
            ai:Error err = error ai:LlmConnectionError("Error while connecting to the model", response);
            span.close(err);
            return err;
        }

        Candidate[]? candidates = response.candidates;
        if candidates is () || candidates.length() == 0 {
            ai:Error err = error ai:LlmInvalidResponseError(buildEmptyCandidatesMessage(response));
            span.close(err);
            return err;
        }
        Candidate candidate = candidates[0];

        UsageMetadata? usage = response.usageMetadata;
        if usage is UsageMetadata {
            int? inputTokens = usage.promptTokenCount;
            if inputTokens is int {
                span.addInputTokenCount(inputTokens);
            }
            int? outputTokens = usage.candidatesTokenCount;
            if outputTokens is int {
                span.addOutputTokenCount(outputTokens);
            }
        }
        string? finishReason = candidate.finishReason;
        if finishReason is string {
            span.addFinishReason(finishReason);
        }

        ai:ChatAssistantMessage message = convertCandidateToAssistantMessage(candidate);
        span.addOutputMessages(message);
        span.addOutputType(observe:TEXT);
        span.close();
        return message;
    }

    # Sends a chat request to the model and generates a value that belongs to the type
    # corresponding to the type descriptor argument.
    #
    # + prompt - The prompt to use in the chat messages
    # + td - Type descriptor specifying the expected return type format
    # + return - Generates a value that belongs to the type, or an error if generation fails
    isolated remote function generate(ai:Prompt prompt, @display {label: "Expected type"} typedesc<anydata> td = <>) returns td|ai:Error = @java:Method {
        'class: "io.ballerina.lib.ai.google.gemini.Generator"
    } external;

    # Builds a Gemini `generateContent` request from the normalized `ai` chat messages.
    # System messages are collapsed into a single `systemInstruction`; user, assistant
    # (including tool calls) and function-result messages become `contents` entries.
    #
    # + messages - The chat messages, or a single user message
    # + tools - Tool definitions to expose as function declarations
    # + stop - Optional stop sequence
    # + return - The assembled request, or an `ai:Error` if a message cannot be converted
    private isolated function buildGenerateContentRequest(ai:ChatMessage[]|ai:ChatUserMessage messages,
            ai:ChatCompletionFunctions[] tools, string? stop) returns GenerateContentRequest|ai:Error {
        Content[] contents = [];
        Content? systemInstruction = ();

        if messages is ai:ChatUserMessage {
            contents.push({role: GEMINI_ROLE_USER, parts: [{text: check getChatMessageStringContent(messages.content)}]});
        } else {
            foreach ai:ChatMessage message in messages {
                if message is ai:ChatSystemMessage {
                    string systemText = check getChatMessageStringContent(message.content);
                    if systemInstruction is Content {
                        systemInstruction.parts.push({text: systemText});
                    } else {
                        systemInstruction = {parts: [{text: systemText}]};
                    }
                } else if message is ai:ChatUserMessage {
                    contents.push({role: GEMINI_ROLE_USER, parts: [{text: check getChatMessageStringContent(message.content)}]});
                } else if message is ai:ChatAssistantMessage {
                    Content? assistantContent = buildAssistantContent(message);
                    if assistantContent is Content {
                        contents.push(assistantContent);
                    }
                } else if message is ai:ChatFunctionMessage {
                    contents.push(buildFunctionResponseContent(message));
                }
            }
        }

        GenerationConfig generationConfig = {
            temperature: self.temperature,
            maxOutputTokens: self.maxTokens
        };
        decimal? topP = self.topP;
        if topP is decimal {
            generationConfig.topP = topP;
        }
        int? topK = self.topK;
        if topK is int {
            generationConfig.topK = topK;
        }
        if stop is string {
            generationConfig.stopSequences = [stop];
        }

        GenerateContentRequest request = {contents, generationConfig};
        if systemInstruction is Content {
            request.systemInstruction = systemInstruction;
        }
        if tools.length() > 0 {
            request.tools = [{functionDeclarations: convertTools(tools)}];
        }
        return request;
    }
}

# Maps a Gemini response candidate onto a normalized `ai:ChatAssistantMessage`.
# Text parts are concatenated into `content`; `functionCall` parts become `toolCalls`.
#
# + candidate - The first candidate from a `generateContent` response
# + return - The normalized assistant message
isolated function convertCandidateToAssistantMessage(Candidate candidate) returns ai:ChatAssistantMessage {
    ai:ChatAssistantMessage assistantMessage = {role: ai:ASSISTANT};
    Content? content = candidate.content;
    if content is () {
        return assistantMessage;
    }

    string textContent = "";
    ai:FunctionCall[] toolCalls = [];
    foreach Part part in content.parts {
        string? text = part.text;
        if text is string {
            textContent += text;
        }
        FunctionCall? functionCall = part.functionCall;
        if functionCall is FunctionCall {
            toolCalls.push({name: functionCall.name, arguments: functionCall.args ?: {}});
        }
    }

    if textContent.length() > 0 {
        assistantMessage.content = textContent;
    }
    if toolCalls.length() > 0 {
        assistantMessage.toolCalls = toolCalls;
    }
    return assistantMessage;
}

# Builds a `model`-role content from an assistant message, emitting text and/or
# `functionCall` parts. Returns `()` when the message carries neither content nor
# tool calls, so the caller can omit it rather than send an empty (or empty-text)
# part, which Gemini rejects.
#
# + message - The assistant message to convert
# + return - The corresponding Gemini content, or `()` when there is nothing to send
isolated function buildAssistantContent(ai:ChatAssistantMessage message) returns Content? {
    Part[] parts = [];
    string? content = message?.content;
    if content is string && content.length() > 0 {
        parts.push({text: content});
    }
    ai:FunctionCall[]? toolCalls = message.toolCalls;
    if toolCalls is ai:FunctionCall[] {
        foreach ai:FunctionCall functionCall in toolCalls {
            parts.push({functionCall: {name: functionCall.name, args: functionCall.arguments}});
        }
    }
    if parts.length() == 0 {
        return ();
    }
    return {role: GEMINI_ROLE_MODEL, parts};
}

# Builds a `functionResponse` content from a tool-result message. It is sent with
# the `user` role: the Gemini v1beta `Content.role` field accepts only `user` and
# `model` (not `function`), so tool results are attributed to `user`. This choice
# is locked by `testChatMultiTurnToolConversation`. The result string is parsed as
# a JSON object when possible, otherwise wrapped as `{"result": <text>}`.
#
# + message - The function/tool result message
# + return - The corresponding Gemini content
isolated function buildFunctionResponseContent(ai:ChatFunctionMessage message) returns Content {
    map<json> response = {};
    string? content = message?.content;
    if content is string {
        json|error parsed = content.fromJsonString();
        response = parsed is map<json> ? parsed : {result: content};
    }
    return {role: GEMINI_ROLE_USER, parts: [{functionResponse: {name: message.name, response}}]};
}

# Converts `ai` tool definitions into Gemini function declarations, sanitizing the
# parameter JSON schema of keywords Gemini does not accept.
#
# + tools - The tool definitions
# + return - The function declarations for a single Gemini `Tool`
isolated function convertTools(ai:ChatCompletionFunctions[] tools) returns FunctionDeclaration[] {
    FunctionDeclaration[] declarations = [];
    foreach ai:ChatCompletionFunctions tool in tools {
        FunctionDeclaration declaration = {name: tool.name, description: tool.description};
        map<json>? params = tool?.parameters;
        if params is map<json> {
            json sanitized = sanitizeGeminiSchema(params);
            if sanitized is map<json> {
                declaration.parameters = sanitized;
            }
        }
        declarations.push(declaration);
    }
    return declarations;
}

# Recursively removes JSON-schema keywords unsupported by Gemini's function-calling
# schema (see `UNSUPPORTED_SCHEMA_KEYS`) from a schema value.
#
# + schema - The schema (object, array, or scalar) to sanitize
# + return - The sanitized schema
isolated function sanitizeGeminiSchema(json schema) returns json {
    if schema is map<json> {
        map<json> result = {};
        foreach [string, json] [key, value] in schema.entries() {
            if UNSUPPORTED_SCHEMA_KEYS.indexOf(key) is int {
                continue;
            }
            result[key] = sanitizeGeminiSchema(value);
        }
        return result;
    }
    if schema is json[] {
        return schema.'map(item => sanitizeGeminiSchema(item));
    }
    return schema;
}

isolated function getChatMessageStringContent(ai:Prompt|string prompt) returns string|ai:Error {
    if prompt is string {
        return prompt;
    }
    string[] & readonly strings = prompt.strings;
    anydata[] insertions = prompt.insertions;
    string promptStr = strings[0];
    foreach int i in 0 ..< insertions.length() {
        string str = strings[i + 1];
        anydata insertion = insertions[i];

        if insertion is ai:TextDocument|ai:TextChunk {
            promptStr += insertion.content + " " + str;
            continue;
        }

        if insertion is ai:TextDocument[] {
            foreach ai:TextDocument doc in insertion {
                promptStr += doc.content + " ";
            }
            promptStr += str;
            continue;
        }

        if insertion is ai:TextChunk[] {
            foreach ai:TextChunk doc in insertion {
                promptStr += doc.content + " ";
            }
            promptStr += str;
            continue;
        }

        if insertion is ai:Document {
            return error ai:Error("Only Text Documents are currently supported.");
        }

        promptStr += insertion.toString() + str;
    }
    return promptStr.trim();
}

isolated function convertMessageToJson(ai:ChatMessage[]|ai:ChatMessage messages) returns json|ai:Error {
    if messages is ai:ChatMessage[] {
        return messages.'map(msg => msg is ai:ChatUserMessage|ai:ChatSystemMessage ? check convertMessageToJson(msg) : msg);
    }
    return messages !is ai:ChatUserMessage|ai:ChatSystemMessage ? messages :
        {role: messages.role, content: check getChatMessageStringContent(messages.content), name: messages.name};
}
